### ISSUE TITLE
Update example for rocket_contrib::databases?

### ISSUE THREAD

**Issue by paulvt** [davidpdrsn/graphql-app-example#17]
I already have a recent Rocket application that uses the `rocket_contrib::database` module.
This seemed to me, as a beginner, the easier way to integrate a database using the Diesel driver.
However, I cannot seem to make it work if I try to adapt this example for it?

Given I have:
```rust
#[database("foo_db")]
pub struct DbConn(diesel::SqliteConnection);
````

I tried to put a `DbConn` in `Context`, but that doesn't seem to be possible; `DbConn` does not implement `Sync`? I also tried to use `DbConn` as `Context`, given that `FromRequest` is implemented but then I really get pages of warnings that I will not repeat here.

Would you consider adapting the example to use `rocket_contrib::databases` instead of a custom DB pooling implementation?

**Comment by davidpdrsn** [comment]
I had similar issues when I created the app I work on for work, which this project is based on. I'll try giving it another shot to see if I can get further this time. I don't exactly when that'll happen.

**Comment by sd2k** [comment]
FWIW I worked around this by putting the `diesel` connection in my context and creating the context in my routes:

```
// Context stuff
pub struct Context(diesel::PgConnection);
impl juniper::Context for Context;

// Database stuff
#[database("foo")
pub struct DbConn(diesel::PgConnection)

// Handler
#[get("/graphql?<request>")]
fn get_graphql_handler(
    db: DbConn,
    request: juniper_rocket::GraphQLRequest,
    schema: State<Schema>,
) -> juniper_rocket::GraphQLResponse {
    let context = Context(db.0);
    request.execute(&schema, &context)
}
```

It was a while ago, but I think it was the only way I could implement my `Context` in a separate graphql crate which doesn't know anything about Rocket (since I also ended up deploying an AWS lambda version using `serverless-rust` which doesn't use Rocket).
