### ISSUE TITLE
Unable to run setup script completely

### ISSUE THREAD

**Issue by onx2** [davidpdrsn/graphql-app-example#66]
Hi! I'm just starting out with Rust so this is all _very_ new to me so I wanted to say thanks for creating this example repo, it's been helpful :smile: 

I am hitting an error when running `bash bin/setup` though - have you seen or know about this error?

```  bash
Compiling rocket_http v0.4.5
error: proc macro panicked
   --> /home/onx2/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket_http-0.4.5/src/parse/uri/parser.rs:119:34
    |
119 |             let path_and_query = pear_try!(path_and_query(is_pchar));
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Option::unwrap()` on a `None` value
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `rocket_http`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
^C  Building [====================================================>  ] 195/201: diesel 
```

As an aside, I had to change the database url in the setup script to include the user and password, so something like this:
```bash
echo DATABASE_URL=postgres://username:password@localhost/graphql-app-example >> .env
```

**Comment by davidpdrsn** [comment]
Thanks for noticing! It seems something broke between a version of Rocket and the latest nightly rust version https://github.com/SergioBenitez/Rocket/issues/1401. Running `cargo update` fixed it for me. I pushed the changes in 755cd9192654e so if you pull things should work again.

Regarding the username and password for postgres, I think that depends on how postgres is configured on your machine. When I use `createdb` to make a database the username becomes the same as my OS user, and the password empty. Those are also the defaults for connecting to the database.

**Comment by onx2** [comment]
It's working now, thanks for the quick response!

Do you mind explaining why there is a `users` and `userConnections` query? @davidpdrsn 

I've seen the connections / edges / node pattern with the relay spec, but I thought that would replace `users`? Or is it simply to show different options?
